fio.contracts/contracts/fio.treasury/fio.treasury.cpp

add logic to init the time if it has yet to be initialized..
NOTE -- this (was edited in git web client to get into develop ) and needs regression tested on one of our servers before being used elsewhere

 init the time if it has yet to be initialized

---

LICENSE

Clarify entity name
FIO Foundation is redundant, should be Foundation for Interwallet Operability

Update LICENSE (FIO Foundation to Foundation for Interwallet Operability)

---

fio.contracts/contracts/eosio.msig/src/eosio.msig.cpp
fio.contracts/contracts/fio.address/fio.address.cpp
fio.contracts/contracts/fio.common/fioerror.hpp
fio.contracts/contracts/fio.fee/fio.fee.cpp
fio.contracts/contracts/fio.request.obt/fio.request.obt.cpp
fio.contracts/contracts/fio.system/include/fio.system/native.hpp
fio.contracts/contracts/fio.system/src/fio.system.cpp
fio.contracts/contracts/fio.system/src/voting.cpp
fio.contracts/contracts/fio.token/src/fio.token.cpp
fio.contracts/contracts/fio.treasury/fio.treasury.cpp

- Change error code to 400 for invalid transaction size

Update transaction size error code to 400

---

libraries/chain/include/eosio/chain/fioio/pubkey_validation.hpp
plugins/chain_plugin/chain_plugin.cpp

The discussion on if the implementation is required on other calls is necessary for this PR to continue.

Add support for PUB_K1 prefix on 4 endpoints

---

plugins/chain_plugin/chain_plugin.cpp

Issue from the latest prefix PR.

Issue with hashing of pubkey inside get_fio_balance

---

plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp

add the more attribute, which will contain the number of rows remaining in the table.

add the more attribute, containing number of results remaining in the table

---

fio.contracts/contracts/fio.address/fio.address.cpp

Solution to issue https://github.com/fioprotocol/fio/issues/42:
- Changed step parameter in decrcounter to &step

make step in decrcounter pass by reference

---

fio.contracts/contracts/fio.address/fio.address.abi
fio.contracts/contracts/fio.address/fio.address.cpp
fio.contracts/contracts/fio.common/fio.common.hpp
libraries/chain/include/eosio/chain/fioio/actionmapping.hpp
plugins/chain_api_plugin/chain_api_plugin.cpp
plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp

Add ability to transfer FIO Address to new owner
Adding xferaddress action with associated exception handling
Adding /transfer_fio_address end point
Adding new fee: transfer_fio_address

Transfer FIO Address to new owner

---

fio.contracts/contracts/fio.system/src/voting.cpp

this PR will update voting power after fees are collected when an account is used to reg proxy

update voting power after fees collected on regproxy

---

fio.contracts/contracts/fio.request.obt/fio.request.obt.cpp

update status to cancelled

---

plugins/chain_api_plugin/chain_api_plugin.cpp
plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp

Reverts fioprotocol/fio#119 - @edrotthoff Will be integration get_actor to history/0.9.2 and develop for now.

Revert "add new endpoint for get_actor"

---

fio.contracts/contracts/fio.treasury/fio.treasury.cpp

These are the changes necessary to merge develop to master.

Rebasing develop with master

---

libraries/chain/include/eosio/chain/fioio/actionmapping.hpp

Adds unlinkauth action to actionmapping header

add unlinkauth to actionmapping

---

fio.contracts/contracts/fio.treasury/fio.treasury.cpp
libraries/chain/include/eosio/chain/fioio/actionmapping.hpp

This PR brings in the action mapping for unlinkauth.

Develop -> Master (v1.1.0)(fix)

---

fio.contracts/contracts/fio.fee/fio.fee.cpp
fio.contracts/contracts/fio.fee/fio.fee.hpp

Revert "HOTFIX -- MERGE BY ERIC ONLY,  fee voting is broken on main net, Fix secondary index in fees table lookups in fee update"

---

fio.contracts/contracts/fio.address/fio.address.cpp

This PR enables transfer_fio_domain.

Remove assert enabling xferdomain

---

plugins/chain_plugin/chain_plugin.cpp

https://github.com/fioprotocol/fio/commit/f48a1675bf9ce4607099ead6f61bc4b568f113a7 - Fix get_account to look up voter information by secondary index

look up voter by secondary index in get_account

---

fio.contracts/contracts/fio.common/fioerror.hpp
fio.contracts/contracts/fio.system/include/fio.system/native.hpp
libraries/chain/apply_context.cpp
libraries/chain/controller.cpp
libraries/chain/eosio_contract.cpp
libraries/chain/eosio_contract_abi.cpp
libraries/chain/include/eosio/chain/account_object.hpp
libraries/chain/include/eosio/chain/apply_context.hpp
libraries/chain/include/eosio/chain/contract_types.hpp
libraries/chain/include/eosio/chain/controller.hpp
libraries/chain/include/eosio/chain/eosio_contract.hpp
libraries/chain/include/eosio/chain/fioaction_object.hpp
libraries/chain/include/eosio/chain/fioio/actionmapping.hpp
libraries/chain/include/eosio/chain/types.hpp
plugins/chain_api_plugin/chain_api_plugin.cpp
plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp

this PR moves the whitelist changes (combined with everything in develop which includes FIP 2,3,4. into a project branch for the gemini initiative..

merge action whitelist over to gemini project dev branch. Tidy-ing up branched

---

fio.contracts/contracts/fio.common/fioerror.hpp
fio.contracts/contracts/fio.system/include/fio.system/native.hpp
libraries/chain/apply_context.cpp
libraries/chain/controller.cpp
libraries/chain/eosio_contract.cpp
libraries/chain/eosio_contract_abi.cpp
libraries/chain/include/eosio/chain/apply_context.hpp
libraries/chain/include/eosio/chain/contract_types.hpp
libraries/chain/include/eosio/chain/controller.hpp
libraries/chain/include/eosio/chain/eosio_contract.hpp
libraries/chain/include/eosio/chain/fioaction_object.hpp
libraries/chain/include/eosio/chain/fioio/actionmapping.hpp
libraries/chain/include/eosio/chain/types.hpp
plugins/chain_api_plugin/chain_api_plugin.cpp
plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp

this PR adds a new actions table to state, it also adds two new actions to the core system contract addaction and remaction.
logic is added to apply context to check the new actions table, Also new logic is added to consider a soft fork block time after which the new table will be used.
a new read only action called get_actions is also added.
this code needs some needs some cleanup, and also for the soft forking date to be set for testing and then for final deployment.

gemini Fip 12 changes added.

---

libraries/chain/apply_context.cpp

Update time to July 29.

---

libraries/chain/apply_context.cpp
plugins/chain_plugin/chain_plugin.cpp

This PR has caused some issues with testing other efforts while using this branch as the current development build.

Revert "set fork time to july 20 4:00pm MST"

---

libraries/chain/apply_context.cpp
plugins/chain_plugin/chain_plugin.cpp

this sets the gemini forking deadline for test net rollout of gemini to be Aug 3 2020 6am MST aka 12pm UTC

test net gemini forking deadline

---

libraries/chain/apply_context.cpp
plugins/chain_plugin/chain_plugin.cpp

Wed Sep 23 16:00:00 UTC 2020 Forking Date Set

Add forking date to apply_context.cpp / chain_plugin

---

plugins/chain_api_plugin/chain_api_plugin.cpp
plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp

Implementation for FIP 13
- Add new endpoint for get_pub_addresses
All addresses and token information returned for a target fio_address. 
https://github.com/fioprotocol/fips/blob/master/fip-0013.md

[FIP-13] Implementation - get_pub_addresses

---

libraries/chain/include/eosio/chain/fioio/fio_common_validator.hpp
plugins/chain_plugin/chain_plugin.cpp

Allows get_pub_address to return chain level public address if no token is found and the default chain is assigned.

FIP-18: Chain-level public address

---

programs/clio/httpc.cpp

- Updates to do_txrx method
- Include status_code 400 through 403 in response

[clio] More verbose message on http err

---

programs/clio/main.cpp

- Left out commit for requests

More clio updates

---

programs/clio/main.cpp

- change addresses field to public_addresses in addaddress variant pack

correct public_addresses in variant

---

programs/clio/main.cpp

- Correction to address type, issue found during testing

use string vector for address

---

programs/clio/main.cpp

- Move address lists to end of subcommands
-fix variant ordering

Clio update

---

plugins/chain_plugin/chain_plugin.cpp

Use updated table references for req and obt data

---

plugins/chain_plugin/chain_plugin.cpp

init_time -> req_time
update_time -> obt_time
content -> req_content
obt_metadata -> obt_content

Use new time and content references

---

plugins/history_plugin/history_plugin.cpp

Added condition for idx.end()
https://fioprotocol.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=BD&modal=detail&selectedIssue=BD-2271

v1 history - get_actions update

---

programs/clio/main.cpp

3d6c5a6ed88e673ea240d86f3af0fe266e94ccb0 - disable subcommands - https://fioprotocol.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=BD&modal=detail&selectedIssue=BD-2359

clio - disable address transfer, add_pub, remove_pub, remove_all_pub

---

plugins/chain_plugin/chain_plugin.cpp
programs/clio/main.cpp

https://fioprotocol.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=BD&modal=detail&selectedIssue=BD-2362

Roll back voter table changes to get_account

---

plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp

set defaults for limit and offset, dev test using android studio tests.

fix bug when limit not specified.

---

libraries/chain/eosio_contract.cpp
plugins/chain_plugin/chain_plugin.cpp

This PR modifies the addaction to no longer permit illegal names to be entered into the actions table for the contract name attribute.

BD-2448 BAHAMAS fix bug in add action, allowing illegal entries for contract

---

libraries/chain/controller.cpp

remove local init of actions for prod release.

remove local init of actions for prod release.

---

plugins/chain_plugin/chain_plugin.cpp

add remaining bundle count to results of get_fio_addresses.

Bahamas -- 3.0.1 fix for get_fio_addresses for rem bundle cound

---

plugins/chain_plugin/chain_plugin.cpp

fix for get_fio_addresses for rem bundle cound

---

plugins/chain_plugin/chain_plugin.cpp
scripts/helpers/fio_helper.sh

Release/3.0.x -> master ( Bahamas FIO Release v3.0.1 )

---

plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp

this PR adds staking information to the get_fio_balance call as defined in FIP-21

FIP-21 FIO staking get_fio_balance changes

---

plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp

update the math to compute ROE in get_fio_balance.

FIP-21 -- update math in the computation of the ROE in get_fio_balance

---

plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp

fix roe and threshold calculations.

FIP-21 Staking   fix roe and threshold calculation.

---

plugins/chain_plugin/chain_plugin.cpp

update roe calc to match contracts

FIP-21 Staking  update roe calc to match contracts

---

plugins/chain_plugin/chain_plugin.cpp

output ROE to the full number of decimal places.

FIP-21 Staking output the value to the full number of decimal places

---

plugins/chain_plugin/chain_plugin.cpp

FIP-21 Staking mandate 15 decimal places on roe from get_fio_balance

---

plugins/chain_plugin/chain_plugin.cpp

modify the logic of get locks to only return future locking periods, also adapt the lock amount and remaining lock amount accordingly, so now by definition, the payouts_performed returned will ALWAYS be zero.

FIP-21 Staking remove expired but not yet claimed locking periods from the get_locks results

---

plugins/chain_plugin/chain_plugin.cpp

namexpiration forced set to FIP-31 date

Force fionames expiration to future date on getters

---

plugins/chain_plugin/chain_plugin.cpp

these changes integrate the latest revision to staking and staking global state described here
https://fioprotocol.atlassian.net/wiki/spaces/FC/pages/451280908/Proposed+Staking+Changes+2021-09-30

FIP-21 Staking -- integrate latest state model and revised staking, use last_ctp, last_gsrp for ROE

---

plugins/chain_plugin/chain_plugin.cpp

Story: https://fioprotocol.atlassian.net/jira/software/c/projects/BD/boards/2?modal=detail&selectedIssue=BD-3034

Wildcard NFT result for all token_id lookups w/ get_nfts_contract

---

plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp

BD-2143: fix bug where more field was returning name on get_producers

---

plugins/chain_plugin/chain_plugin.cpp

add logic to protect math operations from returning unexpected results.

BD-3853 add protective logic to operations in get_fio_balance

---

libraries/chain/controller.cpp

BD-3939: Updated controller to remove dev-specific logic

---

libraries/chain/include/eosio/chain/fioio/fio_common_validator.hpp
libraries/chain/include/eosio/chain/fioio/fioerror.hpp
plugins/chain_api_plugin/chain_api_plugin.cpp
plugins/chain_plugin/chain_plugin.cpp
plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp

new getters and endpoints in accordance with FIP-40 spec.

FIP-40 changes to FIO Core.

---

libraries/chain/include/eosio/chain/config.hpp

BD-4564 set default max cpu to previous value

BD-4564 set default max cpu to previous value

---

README.md
scripts/fio_build.sh

BD-4545: Updated readme and build help

---

libraries/chain/controller.cpp

BD-4572 commented out dev-specific logic to genesis chain locally
TestNet/MainNet facing change to allow chain to run

BD-4572 commented out dev-specific logic to genesis chain

---

libraries/chain/include/eosio/chain/config.hpp

Final 3.5.x merge including incorporation of get fio balance no error on multiple locks change.

Release/3.5.x Update from 3.5.x-dev

---

scripts/fio_build.sh
scripts/helpers/fio_helper.sh

Ubuntu 20 and 22 build and deploy support

---

README.md

BD-4617: Updated build section in readme, incl compatibility, dependencies

---

README.md

Ubuntu 20 and 22 Upgrade (BD-4617)

---

scripts/fio_build.sh
scripts/fio_install.sh

Fixed fio_install verification of build.

Ubuntu 20 and 22 Upgrade: Build verification fix

---

scripts/fio_build.sh
scripts/fio_install.sh

BD-4717: Fixed build verification, added boost_root.

Ubuntu 20 and 22 Upgrade: Build verification fix #2

---

scripts/helpers/fio_helper.sh

Fixed test of install location for previous builds to check for actual content

BD-4617: Previous install test update

---

docs/macos-sonoma-build.md

S3 bucket location and formatting

MacOS build Readme updates
