fio.contracts/contracts/fio.system/src/voting.cpp
Multiple action calls did not match v1.0 API spec. 404->400 error response changes along with added proxy validation on voteproxy.
=> Update error messaging in voting.cpp

fio.contracts/contracts/fio.system/src/producer_pay.cpp, fio.contracts/contracts/fio.treasury/fio.treasury.cpp, fio.contracts/contracts/fio.treasury/fio.treasury.hpp
Hotfix from PR #63 
> this PR modifies the logic used to check that the chain has been activated, we add a check to the thresh_voted_fio_time so as to ensure that if the chain has been activated, we will not lose activation if votes are lost...
=> modify BPclaim to have vote shares sorted by votes, mod logic to check if chain is activated.

fio.contracts/contracts/fio.system/src/voting.cpp, fio.contracts/contracts/fio.treasury/fio.treasury.cpp
this PR merges the hot fixes placed into the master branch..
this PR fixes the doubling of voting weight when a user sets a proxy for voting.
this PR fixes the providing of the correct BPs into the vote shares when there are more than 42 BPs active.
these changes have NOT been tested in this form. it is recommended that we set up a server with these changes and the shortened claim period for pawel to test after these changes are merged into develop.
=> fix doubling of voting weight when a proxy is voted for, fix BP claim  when over 42 active BPs are present.

plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
this PR adds these new endpoints which provide paging of results.
--DEV TESTS PERFORMED --
this was tested using the soapui tests.
this was tested by loading the presale domains and presale addresses and verifying that the paging works as expected..
test performed
1) do not specify limit or offset, see that all results are returned.
2) specify result and offset, see that the correct number of results are returned and that they being at the expected index in the table.
3) specify a pub key with no results, verify the 404 error returned.
=> add get_fio_domains and get_fio_addresses to API

fio.contracts/contracts/fio.treasury/fio.treasury.cpp
this PR ensures the vote shares is filled with the correct number of BPs 
this needs tested on testnet.
=> fix logic error, increment bpcount when we place into table

fio.contracts/contracts/fio.treasury/fio.treasury.cpp
prototalvote orders bps in the following way, active BPs in order of highest votes to least, then not active BPs from lowest votes to highest....
=> traverse the prototalvote index from the begin instead of end

fio.contracts/contracts/fio.address/fio.address.abi
- Altered domains table type for expiration field to uint64 type
- Testing: Spun up local test chain with old abi, set contract to new abi and was able to continue registering new fio domains to the table
=> MAS-1653 - Fix type for domain expiration

fio.contracts/contracts/fio.token/src/fio.token.cpp
this PR removes the check on transaction size for the transfer action in the fio.token contract.
code analysis shows that the action already requires system and treasury authority, which requires MSIG of 2/3 plus 1 from producers.
all calls to transfer within the contracts have other max tx size checks or they require auth of an MSIG system account.
TESTING NOTE -- this change will break the MSIG SOAPUI tests, the max size tests (which assume a failure when large tx are sent through propose and updateauth)...these will now succeed and be charged the appropriate byte wise fee.
=> remove transaction size check from fio.token transfer action

fio.contracts/contracts/fio.address/fio.address.cpp
This pre-release version of changes to xferdomain and xferaddress. These changes include:
- Account Creation for new accounts during transfers
- Validation of domain expression in xferdomain
- xferaddress checks the  fio_address is not active proxy & producer.
Testing Server: 34.221.146.4
=> Add account creation, proxy and producer checks

fio.contracts/contracts/eosio.msig/include/eosio.msig/eosio.msig.hpp, fio.contracts/contracts/eosio.msig/src/eosio.msig.cpp, fio.contracts/contracts/fio.system/include/fio.system/native.hpp
this PR modifies the RAM bump on eosio.msig propose and fio.system updateauth, the RAM bump is now computed as the number of bytes in the TX divided by 1000 rounded up, and then multiplied by 1024.
this was tested by running multis tests and seeing that update auth and propose work successfully, more testing is needed to prove the RAM bump is accurate...this will be completed in UAT testing.
=> update ram bump on byte wise fee calls, do size wise ram bump

fio.contracts/contracts/fio.system/include/fio.system/fio.system.hpp, fio.contracts/contracts/fio.system/include/fio.system/native.hpp, fio.contracts/contracts/fio.system/src/fio.system.cpp
- Update several contract actions to reflect implementation of eosio.contracts 1.9
- Updates change several contract actions to use proper const and pass by reference in parameters
=> Update contract action parameters to use const &

plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
The extra unused field was removed to all 3 request API calls.
=> Remove block_num from requests get API call returns.

fio.contracts/contracts/fio.address/fio.address.cpp
This will disable the two contract actions associated with transferring of domain/addresses.
=> Disable xferaddress/xferdomain action calls 

plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
this PR adds a new endpoint get_actor which takes a public key as input and returns the actor name associated with the specified public key
=> add get_actor endpoint to chain_plugin

plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
this pr adds a new endpoint to the chain plugin called get_actor that takes as input fio public key and returns the actor for the specified public key
=> add new endpoint for get_actor

fio.contracts/contracts/fio.fee/fio.fee.cpp, fio.contracts/contracts/fio.fee/fio.fee.hpp
this PR fixes the secondary 128 bit index on the fees table providing lookup by endpoint name hash.
the code that uses the index also needed updating, had a 64 bit variable needing updated to 128
this was tested using a 24 node local testnet on azure, and testing with the soap ui tests.
=> HOTFIX -- MERGE BY ERIC ONLY,  fee voting is broken on main net, Fix secondary index in fees table lookups in fee update

fio.contracts/contracts/fio.address/fio.address.cpp, fio.contracts/contracts/fio.fee/fio.fee.cpp, fio.contracts/contracts/fio.fee/fio.fee.hpp
this PR resolves the issue with fees not being written into the fees table after votes are processed.
this PR enforces that 15 votes are needed to vote for fees.
this PR enforces that 15 votes are needed before bundlecount votes will be processed.
these changes need to be tested on a 24 node test net..we need to make tests that will vote the necessary number of votes with active producer keys and such...
=> ERIC TO REVIEW and MERGE please -- fee, and bundle count vote fixes for release/1.0.3

fio.contracts/contracts/fio.address/fio.address.cpp, fio.contracts/contracts/fio.fee/fio.fee.cpp, fio.contracts/contracts/fio.fee/fio.fee.hpp
this PR fixes the indexing on the fiofees table to provide a 128 bit index for end point name hash.
this index is then used by the fee voting median algorithm to compute fees for the fio protocol.
this PR enforces that there must be 15 votes for an endpoint before a new fee will be calculated and updated into the fees table.
This PR also modifies the voting for bundle count, so that there must be 15 votes before votes will be used to calculate the bundle count.
it may be useful to have many BPs set fee multipliers and vote for fees before putting this fix into place to best serve the governance of the fees in the FIO protocol on main net.
this was tested using a 24 node local test net and soapui tests purpose built for testing the setting of fees from fee votes by one producer.
=> Changes to fix the 128 bit index on the fees table, also fix the local var to be uint128 so searching will work properly

programs/clio/main.cpp
- Addition of regaddress subcommand 
- Addition of regdomain subcommand 
Example:
```
clio fioaddress regaddress myaccount adam12345@dapixdev 40000000000 FIO6KyHXyv5LRQRNgtD26SBf8RJdhrbTkoamWnjReYouaBTfQeGsW  
clio fioaddress regdomain myaccount mydomain 40000000000 FIO6KyHXyv5LRQRNgtD26SBf8RJdhrbTkoamWnjReYouaBTfQeGsW  
```
=> Feature/fio#54 clio enhancements - Add regaddress/regdomain subcommands

fio.contracts/contracts/fio.address/fio.address.cpp, fio.contracts/contracts/fio.common/fio.common.hpp, fio.contracts/contracts/fio.common/fioerror.hpp, fio.contracts/contracts/fio.request.obt/fio.request.obt.cpp, fio.contracts/contracts/fio.system/src/voting.cpp, fio.contracts/contracts/fio.token/src/fio.token.cpp, fio.contracts/contracts/fio.tpid/fio.tpid.cpp
this PR fixes this issue https://github.com/fioprotocol/fio/issues/141
this PR ensures that calls to the update tpid have the correct actor and so the correct entry will be made into the voters table going forward.
this PR requires more intensive testing using TPIDs to verify auto proxy is set up correctly whenever a tpid is used and no proxy is set by the calling account.
=> Fixes for TPID auto proxy, issue 141

libraries/chain/include/eosio/chain/fioio/pubkey_validation.hpp, plugins/chain_plugin/chain_plugin.cpp
Since the PUB_K1 keys are hashed using the prefix, the changes that were implemented prior need to be reverted.
=> Revert Pub_K1 replace solution.

fio.contracts/contracts/fio.fee/fio.fee.cpp
this PR removes updating of fees from fee voting actions, this should allow the BPs to get in over 15 votes and we can see if the fee computations on the block boundaries hold up with 21 votes.
If not we will need to consider extending the cpu limits of fio as the next short term iteration.
=> Remove fee update from fee voting 

programs/clio/main.cpp
Reverts fioprotocol/fio#144 ( will be released separately after 1.1.0 release )
=> Revert "Feature/fio#54 clio enhancements - Add regaddress/regdomain subcommands"

fio.contracts/contracts/fio.fee/fio.fee.cpp
This PR removes the assertion when a fee is voted 0, this is permitted.
=> get rid of assert when fee ratio fee is 0

fio.contracts/contracts/fio.system/src/producer_pay.cpp
This PR will remove the computation of the fees from the unblock.
the fee computations need testing, and so its best to not have this untested code in such a critical area of the system.
=> comment out the onblock running of fee computation.

fio.contracts/contracts/fio.common/fioerror.hpp, fio.contracts/contracts/fio.system/include/fio.system/native.hpp, libraries/chain/apply_context.cpp, libraries/chain/controller.cpp, libraries/chain/eosio_contract.cpp, libraries/chain/eosio_contract_abi.cpp, libraries/chain/include/eosio/chain/account_object.hpp, libraries/chain/include/eosio/chain/apply_context.hpp, libraries/chain/include/eosio/chain/contract_types.hpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/eosio_contract.hpp, libraries/chain/include/eosio/chain/fioaction_object.hpp, libraries/chain/include/eosio/chain/fioio/actionmapping.hpp, libraries/chain/include/eosio/chain/types.hpp, plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
this PR is for information purposes only.
This PR makes a new table in state called fioaction, this table holds the list of action names that are permitted to execute in the fio protocol..
the FIO controller chain initialization has been kludged to init the set of allowed actions.
the apply context is modified to read the new table and throw an error if the action name is not present in the table.
A new action is added to the system contract called updateacts, this inserts a new action into the fioaction table. 
this example is to only be used as a proof of concept....final protocol designs will be finalized the week of July 9.
=> example of using a table in state to replace action mapping in code.

libraries/chain/controller.cpp
this PR adds the actions required to launch the BIOS node of a local test net, this provides the use of the actions pertaining to token issuance, reg of bps, voting of bps, creation of accounts, setting of contracts and other necessary functions performed by the BIOS node early in the genesis process of a local dev net, or private test net. We add the actions used early in the process to the chains state by adding them in the controller init_database method (which is only called at genesis) this provides the use of the actions used by the BIOS node. Other actions are added later in the startup after the BIOS node is retired, this permits us to add actions to the system without having to version the code in the chain core. (we can add actions to the launch scripts instead of modifying the …
=> add the actions to the actions table required for local dev test nets

libraries/chain/include/eosio/chain/exceptions.hpp, libraries/chain/include/eosio/chain/fioio/fioerror.hpp, plugins/http_plugin/http_plugin.cpp
The 'Request signature not valid or not allowed.' gets returned when a user does not have permission attempts to execute a transaction owned by another user.
The string was renamed 'Request signature is not valid or this user is not allowed to sign this transaction.' to allow for a more general response.
=> invalid_signature return string rename.

programs/clio/main.cpp
- change subcommand ordering to tpid max_fee for some actions
- move away from fio.common/keyops.hpp
=> fix max_fee parameter ordering

programs/clio/main.cpp
- Corrected improper parameter ordering for regaddress, regdomain
- fio_domain parameter was using fio_address string (non-impacting)
- Correct improper ordering of actor on new funds requesting
=> Finishing updates on clio

programs/clio/main.cpp
Fixes:
- content field missing from newfundsrequest action pack
- public name conflict and missing fields for domain set_pub
- parameter ordering, max_fee last, fio_addresses before actor
=> Fixes to clio subcommands

plugins/chain_plugin/chain_plugin.cpp
Update to v1/chain/get_account
Voters table will be migrated to voters2 in future contract release. This update ensures calls to get_account in chain_plugin searches either the voters or voters2 table for reliable data until all nodes have had a chance to update.
=> add handling for voters2 table to get_account

plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
This PR adds signed transaction reference for`add_bundled_transactions` to the chain plugin.
=> [FIP-11.a] Add API endpoint for addbundles action

plugins/chain_plugin/chain_plugin.cpp
With the new time lookups, changes were needed on index position searching on obt and req lookups.
=> Fix index positions for new table structure on obt and req data

plugins/chain_plugin/chain_plugin.cpp
There was an issue with how the loop inside get_obt_data was iterating through the table records. This splits up the offset between both table lookups as well sets the proper loop limit.
=> Set explicit math and bugfix for get_obt_data

plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
these changes add the bundle count to the address data returned for get_fio_names
these changes implement FIP-25.   https://github.com/fioprotocol/fips/blob/master/fip-0025.md
a new attribute is added to the results for addresses to note the bundle count for the address
this was tested by running the javascript test on the local dev build.
=> [FIP-25] add bundle count to get fio names results

libraries/chain/controller.cpp
this interferes with an operational sync of a node, do this in develop with a build switch instead.
=> get rid of action init on genesis

plugins/chain_plugin/chain_plugin.cpp
This removes the expiration validation on avail_check. Only non-burned addresses and domains will return is_registered: true
=> Remove expiration validation on avail_check

libraries/chain/controller.cpp, libraries/chain/eosio_contract.cpp, libraries/chain/include/eosio/chain/eosio_contract.hpp
set a block boundary for the use of the actions table to get the system accounts in the Fio Protocol. any block time after the 2.0.0 release is fine to use, we chose this block time arbitrarily late in march.
The new logic using the actions table requires the actions table be populated for playbacks. so we want to use the new logic AFTER the table has been fully populated, we chose a date and time after the 2.0.0 release of FIO.
=> BAHAMAS --replay testing, set block boundary after release 2.0.0 for new logic

libraries/chain/controller.cpp, libraries/chain/eosio_contract.cpp
NOTE -- these changes must be fully release playback tested before any test net rollout is considered!!
Dev net was not joining the network correctly after the network was booted with 2.0.x-dev
There are 2 issues one must pay attention to when doing fork testing on dev net..
For the new version being upgraded onto the dev net: 
1) Ensure the controller.cpp is compatible with the boot version of dev tools.  Identify if the controller.cpp contain any duplicate actions with the version of dev tools used to start the dev net in its boot sequence. (REMOVE any duplicated actions between dev tools add actions, and the controller.cpp create actions).
2) Since dev net genesis block time will ALWAYS be greater than any block deadlines used in the code to permit accurate main net playback, we must …
=> BAHAMAS -- dev net fork testing -- ensure that sync is clean when dev net is tested

scripts/helpers/fio_helper.sh
These changes have been approved and merged into eosio master
https://github.com/EOSIO/eos/blob/81c0e58f69bf80a9a20ecd3e9a452c306bf818ee/scripts/helpers/eosio.sh#L236
=> Fix boost path error on ubuntu and mac builds

plugins/chain_plugin/chain_plugin.cpp
rework rarte of exchange calculations
use long double type to protect against overflow and also to maintain accuracy of calculations
=> FIP-21 Staking rework rate of exchange calculations

plugins/chain_plugin/chain_plugin.cpp
round after the 15th instead of the 9th in roe for get_fio_balance.
=> FIP-21 Staking chain plugin --round after the 15th instead of the 9th.

libraries/chain/include/eosio/chain/fioio/fioerror.hpp, plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
endpoint to get listings by status with an optional parameter of the account name (actor). When filtering by actor, use limit 1000
this PR adds an endpoint `get_escrow_listings` which takes 3 parameters. `status`, `limit`, and `offset` with an optional parameter `actor`. When the actor parameter is omitted, the limit and offset work fine, and only records of that given status are returned. If the actor parameter is provided it will only get the records with the requested status but also filtered on the given actor. The caveat is that the limit must be set to 1000 because of the additional filtering a lower limit will not work properly. 
If there are 100 records and the 10th record matches the actor parameter but the limit is 1, no records are returned because it is not found within that 1 …
=> fio.escrow API Endpoint

libraries/chain/include/eosio/chain/contract_types.hpp
correct type discrepencies inhibiting proper deserialization.
special note --
Testing requirements.
this PR should be tested integrated with a history node to ensure that the trnsloktoks is properly reflected in the history and tx logs.
This PR should be tested with a full playback of the present main net chain.
further testing will be determined by QA, and Eric.
=> BD-3229  FIO STAKING -- correct discrepencies for lockperiodv2

plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
This was changed because of an incorrect bug report.
=> Revert get_producers more variable change

libraries/chain/include/eosio/chain/config.hpp
- [ x] Consensus Changes
***** FORKING CHANGE *****
Value has a significant impact on system performance barring slightly slower producers from validating normal transaction loads. Original EOS implementation uses 3 * default_max_transaction_cpu_usage / 4 (150'000), this is a significant increase from the modified value of default_max_transaction_cpu_usage / 4 (50'000). Positive results testing in Ubuntu 18.04 VM (Oracle VBox), requires scale testing.
=> *Test me* Rollback default_max_transaction_cpu_usage

plugins/chain_plugin/chain_plugin.cpp
Changes supporting FIP-43 https://github.com/fioprotocol/fips/blob/master/fip-0043.md
For get_fee api endpoint, if fio_address is left empty or omitted then the fee amount for the endpoint is provided for bundle eligible actions
=> FIP-43 Get_fee update

libraries/chain/include/eosio/chain/contract_types.hpp, plugins/history_plugin/history_plugin.cpp
Issue: xferescrow does not come up in block explorers for a public_key's derived account 
Fix: Added xferescrow contract type and object to history action filtering
https://fioprotocol.atlassian.net/browse/BD-4250
=> add xferescrow to history action filtering

libraries/chain/include/eosio/chain/config.hpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
FIP-46 make walk time configurable for the node
=> FIP-46 make walk time configurable for the node

plugins/chain_plugin/chain_plugin.cpp
BD-4533 use request address owner instead of key from request
all getters of fio requests are impacted (pending, cancelled, sent, requested).
=> FIP-39 BD-4533 use request address owner instead of key from request

plugins/chain_plugin/chain_plugin.cpp
use the first lock in the set of locks...this makes get fio balance consistent with transfer fio actions on chain.
=> BD-4616 No error on get fio balance

plugins/chain_plugin/chain_plugin.cpp
A locking issue uncovered an error workflow that resulted in a degraded user experience. The error path was deemed overly impactful and was removed to prioritize the correct user experience.
=> Removed error on get_fio_balance on acct having more than 1 lock

scripts/helpers/build_darwin.sh
=> MacOS Build Support: Script update to handle MacOS v11 and v14
